import { Suspense } from "react";
import type { Metadata } from "next";
// import { Source_Code_Pro } from 'next/font/google';
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";
import Loading from "./loading";

const source_code_pro = Noto_Sans_JP({
  // variable: '--font-source-code-pro',
  // weights: [400, 700],
  style: 'normal',
  subsets: ['latin'],
  variable: '--font-noto-sans-jp',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Next.js Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className="font-noto-sans-jp">
      <body className="bg-amber-200 text-slate-700">
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="pt-10 pb-20 px-10 mx-auto max-w-screen-xl w-full">
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
